#!/bin/sh
echo 关闭销售支撑系统-core系统开始...
kill -9 `cat /opt/app/pcm/common-core/main.pid`
echo 关闭商销售支撑系统-admin系统成功...
echo 拷贝编译jar包到应用目录 ...
rm -f /opt/app/pcm/common-core/*.jar
cp -f ${WORKSPACE}/target/common-core-0.0.3-SNAPSHOT.jar 

/opt/app/pcm/common-core/
rm -f /opt/app/pcm/common-core/lib/*
echo 拷贝编译iib目录jar包到应用...
cp -f ${WORKSPACE}/target/lib/* /opt/app/pcm/common-core/lib/
echo 拷贝完成...
echo 开始运行服务...
#后台启动进程
nohup java -jar /opt/app/pcm/common-core/common-core-0.0.3-SNAPSHOT.jar start 8080 8081 >/dev/null  &  echo $! >  /opt/app/pcm/common-core/main.pid
echo 启动完毕.....
