//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.08 at 11:39:02 AM CST 
//


package com.jack.netty.server.config;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="base-info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="server-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="server-root" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="server-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="server-desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="max-income-thread-count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="ssh-info">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="keystore-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="keystore-passwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="keystore-certpasswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="isSSL" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="needClientAuth" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="base-params">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="param" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="listener-infos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="listener" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="listener-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="filter-infos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="filter" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="init-param" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="filter-mapping">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="dispatcher" maxOccurs="unbounded">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="REQUEST"/>
 *                                             &lt;enumeration value="INCLUDE"/>
 *                                             &lt;enumeration value="FORWARD"/>
 *                                             &lt;enumeration value="ERROR"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="url-pattern" type="{http://www.jack.com/nettyserver}servlet-suffix" />
 *                                     &lt;attribute name="servlet-name" type="{http://www.jack.com/nettyserver}splitByOpt" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="filter-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="filter-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="onStartup" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dispather-infos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="servlet" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="init-param" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="servlet-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="servlet-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="servlet-suffix" use="required" type="{http://www.jack.com/nettyserver}servlet-suffix" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="handler-infos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="handler" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="construction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="args">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="arg" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="params" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="handler-class" use="required" type="{http://www.jack.com/nettyserver}package-path" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "baseInfo",
    "listenerInfos",
    "filterInfos",
    "dispatherInfos",
    "handlerInfos"
})
@XmlRootElement(name = "netty-server-info")
public class NettyServerInfo {

    @XmlElement(name = "base-info", required = true)
    protected BaseInfo baseInfo;
    @XmlElement(name = "listener-infos", required = true)
    protected ListenerInfos listenerInfos;
    @XmlElement(name = "filter-infos", required = true)
    protected FilterInfos filterInfos;
    @XmlElement(name = "dispather-infos", required = true)
    protected DispatherInfos dispatherInfos;
    @XmlElement(name = "handler-infos", required = true)
    protected HandlerInfos handlerInfos;

    /**
     * Gets the value of the baseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BaseInfo }
     *     
     */
    public BaseInfo getBaseInfo() {
        return baseInfo;
    }

    /**
     * Sets the value of the baseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseInfo }
     *     
     */
    public void setBaseInfo(BaseInfo value) {
        this.baseInfo = value;
    }

    /**
     * Gets the value of the listenerInfos property.
     * 
     * @return
     *     possible object is
     *     {@link ListenerInfos }
     *     
     */
    public ListenerInfos getListenerInfos() {
        return listenerInfos;
    }

    /**
     * Sets the value of the listenerInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListenerInfos }
     *     
     */
    public void setListenerInfos(ListenerInfos value) {
        this.listenerInfos = value;
    }

    /**
     * Gets the value of the filterInfos property.
     * 
     * @return
     *     possible object is
     *     {@link FilterInfos }
     *     
     */
    public FilterInfos getFilterInfos() {
        return filterInfos;
    }

    /**
     * Sets the value of the filterInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterInfos }
     *     
     */
    public void setFilterInfos(FilterInfos value) {
        this.filterInfos = value;
    }

    /**
     * Gets the value of the dispatherInfos property.
     * 
     * @return
     *     possible object is
     *     {@link DispatherInfos }
     *     
     */
    public DispatherInfos getDispatherInfos() {
        return dispatherInfos;
    }

    /**
     * Sets the value of the dispatherInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispatherInfos }
     *     
     */
    public void setDispatherInfos(DispatherInfos value) {
        this.dispatherInfos = value;
    }

    /**
     * Gets the value of the handlerInfos property.
     * 
     * @return
     *     possible object is
     *     {@link HandlerInfos }
     *     
     */
    public HandlerInfos getHandlerInfos() {
        return handlerInfos;
    }

    /**
     * Sets the value of the handlerInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlerInfos }
     *     
     */
    public void setHandlerInfos(HandlerInfos value) {
        this.handlerInfos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="server-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="server-root" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="server-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="server-desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="max-income-thread-count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="ssh-info">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="keystore-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="keystore-passwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="keystore-certpasswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="isSSL" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="needClientAuth" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="base-params">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="param" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serverName",
        "serverRoot",
        "serverCode",
        "serverDesc",
        "maxIncomeThreadCount",
        "sshInfo",
        "baseParams"
    })
    public static class BaseInfo {

        @XmlElement(name = "server-name", required = true)
        protected String serverName;
        @XmlElement(name = "server-root", required = true)
        protected String serverRoot;
        @XmlElement(name = "server-code", required = true)
        protected String serverCode;
        @XmlElement(name = "server-desc", required = true)
        protected String serverDesc;
        @XmlElement(name = "max-income-thread-count", required = true)
        protected BigInteger maxIncomeThreadCount;
        @XmlElement(name = "ssh-info", required = true)
        protected SshInfo sshInfo;
        @XmlElement(name = "base-params", required = true)
        protected BaseParams baseParams;

        /**
         * Gets the value of the serverName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerName() {
            return serverName;
        }

        /**
         * Sets the value of the serverName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerName(String value) {
            this.serverName = value;
        }

        /**
         * Gets the value of the serverRoot property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerRoot() {
            return serverRoot;
        }

        /**
         * Sets the value of the serverRoot property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerRoot(String value) {
            this.serverRoot = value;
        }

        /**
         * Gets the value of the serverCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerCode() {
            return serverCode;
        }

        /**
         * Sets the value of the serverCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerCode(String value) {
            this.serverCode = value;
        }

        /**
         * Gets the value of the serverDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServerDesc() {
            return serverDesc;
        }

        /**
         * Sets the value of the serverDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServerDesc(String value) {
            this.serverDesc = value;
        }

        /**
         * Gets the value of the maxIncomeThreadCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMaxIncomeThreadCount() {
            return maxIncomeThreadCount;
        }

        /**
         * Sets the value of the maxIncomeThreadCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMaxIncomeThreadCount(BigInteger value) {
            this.maxIncomeThreadCount = value;
        }

        /**
         * Gets the value of the sshInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SshInfo }
         *     
         */
        public SshInfo getSshInfo() {
            return sshInfo;
        }

        /**
         * Sets the value of the sshInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SshInfo }
         *     
         */
        public void setSshInfo(SshInfo value) {
            this.sshInfo = value;
        }

        /**
         * Gets the value of the baseParams property.
         * 
         * @return
         *     possible object is
         *     {@link BaseParams }
         *     
         */
        public BaseParams getBaseParams() {
            return baseParams;
        }

        /**
         * Sets the value of the baseParams property.
         * 
         * @param value
         *     allowed object is
         *     {@link BaseParams }
         *     
         */
        public void setBaseParams(BaseParams value) {
            this.baseParams = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="param" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "param"
        })
        public static class BaseParams {

            @XmlElement(required = true)
            protected List<Param> param;

            /**
             * Gets the value of the param property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the param property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Param }
             * 
             * 
             */
            public List<Param> getParam() {
                if (param == null) {
                    param = new ArrayList<Param>();
                }
                return this.param;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Param {

                @XmlAttribute(name = "param-name", required = true)
                protected String paramName;
                @XmlAttribute(name = "param-value", required = true)
                protected String paramValue;

                /**
                 * Gets the value of the paramName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParamName() {
                    return paramName;
                }

                /**
                 * Sets the value of the paramName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParamName(String value) {
                    this.paramName = value;
                }

                /**
                 * Gets the value of the paramValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParamValue() {
                    return paramValue;
                }

                /**
                 * Sets the value of the paramValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParamValue(String value) {
                    this.paramValue = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="keystore-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="keystore-passwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="keystore-certpasswd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="isSSL" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="needClientAuth" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "keystorePath",
            "keystorePasswd",
            "keystoreCertpasswd"
        })
        public static class SshInfo {

            @XmlElement(name = "keystore-path", required = true)
            protected String keystorePath;
            @XmlElement(name = "keystore-passwd", required = true)
            protected String keystorePasswd;
            @XmlElement(name = "keystore-certpasswd", required = true)
            protected String keystoreCertpasswd;
            @XmlAttribute(name = "isSSL")
            protected Boolean isSSL;
            @XmlAttribute(name = "needClientAuth")
            protected Boolean needClientAuth;

            /**
             * Gets the value of the keystorePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKeystorePath() {
                return keystorePath;
            }

            /**
             * Sets the value of the keystorePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKeystorePath(String value) {
                this.keystorePath = value;
            }

            /**
             * Gets the value of the keystorePasswd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKeystorePasswd() {
                return keystorePasswd;
            }

            /**
             * Sets the value of the keystorePasswd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKeystorePasswd(String value) {
                this.keystorePasswd = value;
            }

            /**
             * Gets the value of the keystoreCertpasswd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKeystoreCertpasswd() {
                return keystoreCertpasswd;
            }

            /**
             * Sets the value of the keystoreCertpasswd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKeystoreCertpasswd(String value) {
                this.keystoreCertpasswd = value;
            }

            /**
             * Gets the value of the isSSL property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIsSSL() {
                return isSSL;
            }

            /**
             * Sets the value of the isSSL property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIsSSL(Boolean value) {
                this.isSSL = value;
            }

            /**
             * Gets the value of the needClientAuth property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isNeedClientAuth() {
                return needClientAuth;
            }

            /**
             * Sets the value of the needClientAuth property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setNeedClientAuth(Boolean value) {
                this.needClientAuth = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="servlet" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="init-param" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="servlet-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="servlet-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="servlet-suffix" use="required" type="{http://www.jack.com/nettyserver}servlet-suffix" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "servlet"
    })
    public static class DispatherInfos {

        @XmlElement(required = true)
        protected List<Servlet> servlet;

        /**
         * Gets the value of the servlet property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the servlet property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServlet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Servlet }
         * 
         * 
         */
        public List<Servlet> getServlet() {
            if (servlet == null) {
                servlet = new ArrayList<Servlet>();
            }
            return this.servlet;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="init-param" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="servlet-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="servlet-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="servlet-suffix" use="required" type="{http://www.jack.com/nettyserver}servlet-suffix" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "initParam"
        })
        public static class Servlet {

            @XmlElement(name = "init-param", required = true)
            protected List<InitParam> initParam;
            @XmlAttribute(name = "servlet-class", required = true)
            protected String servletClass;
            @XmlAttribute(name = "servlet-name", required = true)
            protected String servletName;
            @XmlAttribute(name = "servlet-suffix", required = true)
            protected String servletSuffix;

            /**
             * Gets the value of the initParam property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the initParam property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInitParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link InitParam }
             * 
             * 
             */
            public List<InitParam> getInitParam() {
                if (initParam == null) {
                    initParam = new ArrayList<InitParam>();
                }
                return this.initParam;
            }

            /**
             * Gets the value of the servletClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServletClass() {
                return servletClass;
            }

            /**
             * Sets the value of the servletClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServletClass(String value) {
                this.servletClass = value;
            }

            /**
             * Gets the value of the servletName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServletName() {
                return servletName;
            }

            /**
             * Sets the value of the servletName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServletName(String value) {
                this.servletName = value;
            }

            /**
             * Gets the value of the servletSuffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServletSuffix() {
                return servletSuffix;
            }

            /**
             * Sets the value of the servletSuffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServletSuffix(String value) {
                this.servletSuffix = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class InitParam {

                @XmlAttribute(name = "param-name", required = true)
                protected String paramName;
                @XmlAttribute(name = "param-value", required = true)
                protected String paramValue;

                /**
                 * Gets the value of the paramName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParamName() {
                    return paramName;
                }

                /**
                 * Sets the value of the paramName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParamName(String value) {
                    this.paramName = value;
                }

                /**
                 * Gets the value of the paramValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParamValue() {
                    return paramValue;
                }

                /**
                 * Sets the value of the paramValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParamValue(String value) {
                    this.paramValue = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="filter" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="init-param" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="filter-mapping">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="dispatcher" maxOccurs="unbounded">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="REQUEST"/>
     *                                   &lt;enumeration value="INCLUDE"/>
     *                                   &lt;enumeration value="FORWARD"/>
     *                                   &lt;enumeration value="ERROR"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="url-pattern" type="{http://www.jack.com/nettyserver}servlet-suffix" />
     *                           &lt;attribute name="servlet-name" type="{http://www.jack.com/nettyserver}splitByOpt" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="filter-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="filter-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="onStartup" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filter"
    })
    public static class FilterInfos {

        @XmlElement(required = true)
        protected List<Filter> filter;
        @XmlAttribute(name = "onStartup")
        protected Boolean onStartup;

        /**
         * Gets the value of the filter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the filter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFilter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Filter }
         * 
         * 
         */
        public List<Filter> getFilter() {
            if (filter == null) {
                filter = new ArrayList<Filter>();
            }
            return this.filter;
        }

        /**
         * Gets the value of the onStartup property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOnStartup() {
            if (onStartup == null) {
                return false;
            } else {
                return onStartup;
            }
        }

        /**
         * Sets the value of the onStartup property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOnStartup(Boolean value) {
            this.onStartup = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="init-param" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="filter-mapping">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="dispatcher" maxOccurs="unbounded">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="REQUEST"/>
         *                         &lt;enumeration value="INCLUDE"/>
         *                         &lt;enumeration value="FORWARD"/>
         *                         &lt;enumeration value="ERROR"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="url-pattern" type="{http://www.jack.com/nettyserver}servlet-suffix" />
         *                 &lt;attribute name="servlet-name" type="{http://www.jack.com/nettyserver}splitByOpt" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="filter-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="filter-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "initParam",
            "filterMapping"
        })
        public static class Filter {

            @XmlElement(name = "init-param", required = true)
            protected List<InitParam> initParam;
            @XmlElement(name = "filter-mapping", required = true)
            protected FilterMapping filterMapping;
            @XmlAttribute(name = "filter-class", required = true)
            protected String filterClass;
            @XmlAttribute(name = "filter-name", required = true)
            protected String filterName;

            /**
             * Gets the value of the initParam property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the initParam property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInitParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link InitParam }
             * 
             * 
             */
            public List<InitParam> getInitParam() {
                if (initParam == null) {
                    initParam = new ArrayList<InitParam>();
                }
                return this.initParam;
            }

            /**
             * Gets the value of the filterMapping property.
             * 
             * @return
             *     possible object is
             *     {@link FilterMapping }
             *     
             */
            public FilterMapping getFilterMapping() {
                return filterMapping;
            }

            /**
             * Sets the value of the filterMapping property.
             * 
             * @param value
             *     allowed object is
             *     {@link FilterMapping }
             *     
             */
            public void setFilterMapping(FilterMapping value) {
                this.filterMapping = value;
            }

            /**
             * Gets the value of the filterClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilterClass() {
                return filterClass;
            }

            /**
             * Sets the value of the filterClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilterClass(String value) {
                this.filterClass = value;
            }

            /**
             * Gets the value of the filterName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFilterName() {
                return filterName;
            }

            /**
             * Sets the value of the filterName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFilterName(String value) {
                this.filterName = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="dispatcher" maxOccurs="unbounded">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="REQUEST"/>
             *               &lt;enumeration value="INCLUDE"/>
             *               &lt;enumeration value="FORWARD"/>
             *               &lt;enumeration value="ERROR"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="url-pattern" type="{http://www.jack.com/nettyserver}servlet-suffix" />
             *       &lt;attribute name="servlet-name" type="{http://www.jack.com/nettyserver}splitByOpt" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dispatcher"
            })
            public static class FilterMapping {

                @XmlElement(required = true)
                protected List<String> dispatcher;
                @XmlAttribute(name = "url-pattern")
                protected String urlPattern;
                @XmlAttribute(name = "servlet-name")
                protected String servletName;

                /**
                 * Gets the value of the dispatcher property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the dispatcher property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDispatcher().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getDispatcher() {
                    if (dispatcher == null) {
                        dispatcher = new ArrayList<String>();
                    }
                    return this.dispatcher;
                }

                /**
                 * Gets the value of the urlPattern property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrlPattern() {
                    return urlPattern;
                }

                /**
                 * Sets the value of the urlPattern property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrlPattern(String value) {
                    this.urlPattern = value;
                }

                /**
                 * Gets the value of the servletName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServletName() {
                    return servletName;
                }

                /**
                 * Sets the value of the servletName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServletName(String value) {
                    this.servletName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="param-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class InitParam {

                @XmlAttribute(name = "param-name", required = true)
                protected String paramName;
                @XmlAttribute(name = "param-value", required = true)
                protected String paramValue;

                /**
                 * Gets the value of the paramName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParamName() {
                    return paramName;
                }

                /**
                 * Sets the value of the paramName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParamName(String value) {
                    this.paramName = value;
                }

                /**
                 * Gets the value of the paramValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParamValue() {
                    return paramValue;
                }

                /**
                 * Sets the value of the paramValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParamValue(String value) {
                    this.paramValue = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="handler" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="construction">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="args">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="arg" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="params" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="handler-class" use="required" type="{http://www.jack.com/nettyserver}package-path" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "handler"
    })
    public static class HandlerInfos {

        @XmlElement(required = true)
        protected List<Handler> handler;

        /**
         * Gets the value of the handler property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the handler property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHandler().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Handler }
         * 
         * 
         */
        public List<Handler> getHandler() {
            if (handler == null) {
                handler = new ArrayList<Handler>();
            }
            return this.handler;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="construction">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="args">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="arg" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="params" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="handler-class" use="required" type="{http://www.jack.com/nettyserver}package-path" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "construction"
        })
        public static class Handler {

            @XmlElement(required = true)
            protected Construction construction;
            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "handler-class", required = true)
            protected String handlerClass;

            /**
             * Gets the value of the construction property.
             * 
             * @return
             *     possible object is
             *     {@link Construction }
             *     
             */
            public Construction getConstruction() {
                return construction;
            }

            /**
             * Sets the value of the construction property.
             * 
             * @param value
             *     allowed object is
             *     {@link Construction }
             *     
             */
            public void setConstruction(Construction value) {
                this.construction = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the handlerClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHandlerClass() {
                return handlerClass;
            }

            /**
             * Sets the value of the handlerClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHandlerClass(String value) {
                this.handlerClass = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="args">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="arg" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="params" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "args"
            })
            public static class Construction {

                @XmlElement(required = true)
                protected Args args;
                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "params")
                protected Boolean params;

                /**
                 * Gets the value of the args property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Args }
                 *     
                 */
                public Args getArgs() {
                    return args;
                }

                /**
                 * Sets the value of the args property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Args }
                 *     
                 */
                public void setArgs(Args value) {
                    this.args = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the params property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isParams() {
                    return params;
                }

                /**
                 * Sets the value of the params property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setParams(Boolean value) {
                    this.params = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="arg" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "arg"
                })
                public static class Args {

                    @XmlElement(required = true)
                    protected List<Arg> arg;

                    /**
                     * Gets the value of the arg property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the arg property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getArg().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Arg }
                     * 
                     * 
                     */
                    public List<Arg> getArg() {
                        if (arg == null) {
                            arg = new ArrayList<Arg>();
                        }
                        return this.arg;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Arg {

                        @XmlAttribute(name = "key")
                        protected String key;
                        @XmlAttribute(name = "value")
                        @XmlSchemaType(name = "anySimpleType")
                        protected String value;

                        /**
                         * Gets the value of the key property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getKey() {
                            return key;
                        }

                        /**
                         * Sets the value of the key property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setKey(String value) {
                            this.key = value;
                        }

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="listener" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="listener-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listener"
    })
    public static class ListenerInfos {

        @XmlElement(required = true)
        protected List<Listener> listener;

        /**
         * Gets the value of the listener property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the listener property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getListener().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Listener }
         * 
         * 
         */
        public List<Listener> getListener() {
            if (listener == null) {
                listener = new ArrayList<Listener>();
            }
            return this.listener;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="listener-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Listener {

            @XmlAttribute(name = "listener-class", required = true)
            protected String listenerClass;

            /**
             * Gets the value of the listenerClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getListenerClass() {
                return listenerClass;
            }

            /**
             * Sets the value of the listenerClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setListenerClass(String value) {
                this.listenerClass = value;
            }

        }

    }

}
