//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.08 at 11:39:02 AM CST 
//


package com.jack.netty.server.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jack.netty.server.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jack.netty.server.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NettyServerInfo }
     * 
     */
    public NettyServerInfo createNettyServerInfo() {
        return new NettyServerInfo();
    }

    /**
     * Create an instance of {@link NettyServerInfo.HandlerInfos }
     * 
     */
    public NettyServerInfo.HandlerInfos createNettyServerInfoHandlerInfos() {
        return new NettyServerInfo.HandlerInfos();
    }

    /**
     * Create an instance of {@link NettyServerInfo.HandlerInfos.Handler }
     * 
     */
    public NettyServerInfo.HandlerInfos.Handler createNettyServerInfoHandlerInfosHandler() {
        return new NettyServerInfo.HandlerInfos.Handler();
    }

    /**
     * Create an instance of {@link NettyServerInfo.HandlerInfos.Handler.Construction }
     * 
     */
    public NettyServerInfo.HandlerInfos.Handler.Construction createNettyServerInfoHandlerInfosHandlerConstruction() {
        return new NettyServerInfo.HandlerInfos.Handler.Construction();
    }

    /**
     * Create an instance of {@link NettyServerInfo.HandlerInfos.Handler.Construction.Args }
     * 
     */
    public NettyServerInfo.HandlerInfos.Handler.Construction.Args createNettyServerInfoHandlerInfosHandlerConstructionArgs() {
        return new NettyServerInfo.HandlerInfos.Handler.Construction.Args();
    }

    /**
     * Create an instance of {@link NettyServerInfo.DispatherInfos }
     * 
     */
    public NettyServerInfo.DispatherInfos createNettyServerInfoDispatherInfos() {
        return new NettyServerInfo.DispatherInfos();
    }

    /**
     * Create an instance of {@link NettyServerInfo.DispatherInfos.Servlet }
     * 
     */
    public NettyServerInfo.DispatherInfos.Servlet createNettyServerInfoDispatherInfosServlet() {
        return new NettyServerInfo.DispatherInfos.Servlet();
    }

    /**
     * Create an instance of {@link NettyServerInfo.FilterInfos }
     * 
     */
    public NettyServerInfo.FilterInfos createNettyServerInfoFilterInfos() {
        return new NettyServerInfo.FilterInfos();
    }

    /**
     * Create an instance of {@link NettyServerInfo.FilterInfos.Filter }
     * 
     */
    public NettyServerInfo.FilterInfos.Filter createNettyServerInfoFilterInfosFilter() {
        return new NettyServerInfo.FilterInfos.Filter();
    }

    /**
     * Create an instance of {@link NettyServerInfo.ListenerInfos }
     * 
     */
    public NettyServerInfo.ListenerInfos createNettyServerInfoListenerInfos() {
        return new NettyServerInfo.ListenerInfos();
    }

    /**
     * Create an instance of {@link NettyServerInfo.BaseInfo }
     * 
     */
    public NettyServerInfo.BaseInfo createNettyServerInfoBaseInfo() {
        return new NettyServerInfo.BaseInfo();
    }

    /**
     * Create an instance of {@link NettyServerInfo.BaseInfo.BaseParams }
     * 
     */
    public NettyServerInfo.BaseInfo.BaseParams createNettyServerInfoBaseInfoBaseParams() {
        return new NettyServerInfo.BaseInfo.BaseParams();
    }

    /**
     * Create an instance of {@link NettyServerInfo.HandlerInfos.Handler.Construction.Args.Arg }
     * 
     */
    public NettyServerInfo.HandlerInfos.Handler.Construction.Args.Arg createNettyServerInfoHandlerInfosHandlerConstructionArgsArg() {
        return new NettyServerInfo.HandlerInfos.Handler.Construction.Args.Arg();
    }

    /**
     * Create an instance of {@link NettyServerInfo.DispatherInfos.Servlet.InitParam }
     * 
     */
    public NettyServerInfo.DispatherInfos.Servlet.InitParam createNettyServerInfoDispatherInfosServletInitParam() {
        return new NettyServerInfo.DispatherInfos.Servlet.InitParam();
    }

    /**
     * Create an instance of {@link NettyServerInfo.FilterInfos.Filter.InitParam }
     * 
     */
    public NettyServerInfo.FilterInfos.Filter.InitParam createNettyServerInfoFilterInfosFilterInitParam() {
        return new NettyServerInfo.FilterInfos.Filter.InitParam();
    }

    /**
     * Create an instance of {@link NettyServerInfo.FilterInfos.Filter.FilterMapping }
     * 
     */
    public NettyServerInfo.FilterInfos.Filter.FilterMapping createNettyServerInfoFilterInfosFilterFilterMapping() {
        return new NettyServerInfo.FilterInfos.Filter.FilterMapping();
    }

    /**
     * Create an instance of {@link NettyServerInfo.ListenerInfos.Listener }
     * 
     */
    public NettyServerInfo.ListenerInfos.Listener createNettyServerInfoListenerInfosListener() {
        return new NettyServerInfo.ListenerInfos.Listener();
    }

    /**
     * Create an instance of {@link NettyServerInfo.BaseInfo.SshInfo }
     * 
     */
    public NettyServerInfo.BaseInfo.SshInfo createNettyServerInfoBaseInfoSshInfo() {
        return new NettyServerInfo.BaseInfo.SshInfo();
    }

    /**
     * Create an instance of {@link NettyServerInfo.BaseInfo.BaseParams.Param }
     * 
     */
    public NettyServerInfo.BaseInfo.BaseParams.Param createNettyServerInfoBaseInfoBaseParamsParam() {
        return new NettyServerInfo.BaseInfo.BaseParams.Param();
    }

}
